services:
  user-service:
    build: ./services/user-services
    container_name: r-user
    restart: always
    ports:
      - "11001:11001"
    env_file:
      - ./services/user-services/.env.dev
    networks:
      - default

networks:
  default:
    driver: bridge
